name: camera_web_integration_tests
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  async: ^2.5.0

  camera_web:
    git:
      url: https://github.com/mtbo-org/flutter-plugins.git
      path: packages/camera/camera_web

  camera_platform_interface:
    git:
      url: https://github.com/mtbo-org/flutter-plugins.git
      path: packages/camera/camera_platform_interface

  cross_file: ^0.3.1
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^0.3.0
