name: camera_windows_example
description: Demonstrates how to use the camera_windows plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  camera_windows:
    git:
      url: https://github.com/mtbo-org/flutter-plugins.git
      path: packages/camera/camera_windows

  camera_platform_interface:
    git:
      url: https://github.com/mtbo-org/flutter-plugins.git
      path: packages/camera/camera_platform_interface

  flutter:
    sdk: flutter

dev_dependencies:
  async: ^2.5.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
