name: camera_example
description: Demonstrates how to use the camera plugin.
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  camera_android:
    git:
      url: https://github.com/mtbo-org/flutter-plugins.git
      path: packages/camera/camera_android

  camera_platform_interface:
    git:
      url: https://github.com/mtbo-org/flutter-plugins.git
      path: packages/camera/camera_platform_interface

  flutter:
    sdk: flutter
  path_provider: ^2.0.0
  quiver: ^3.0.0
  video_player: ^2.1.4

dependency_overrides:
  camera_android:
    path: ..

  camera_platform_interface:
    path: ../../camera_platform_interface

dev_dependencies:
  build_runner: ^2.1.10
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
